name: gestao_legal_pro
description: "Gestão moderna de processos jurídicos, agenda e clientes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  animations: ^2.0.11
  table_calendar: ^3.0.9
  get: ^4.6.6
  get_it: ^7.7.0
  go_router: ^14.2.7
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.6.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  syncfusion_flutter_pdf: ^30.2.5
  docx_to_text: ^1.0.1
  path: ^1.8.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
